version: '3.7'

services:
  server:
    container_name: love-date-backend
    build: .
    ports:
      - 8000:8000
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - loveapp-database          # Uncomment this when using postgres.
       # - fullstack-mysql           # Uncomment this when using mysql.
    networks:
      - fullstack

  loveapp-database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: loveapp-database
    restart: on-failure
    volumes:
      - dbtest:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: loveappRoo7t0lk2o20
      MYSQL_DATABASE: loveapp
      MYSQL_USER: loveapptest
      MYSQL_PASSWORD: loveapptest123
    networks:
      - fullstack

volumes:
  api:
  dbtest:                  # Uncomment this when using postgres.
  # database_mysql:                   # Uncomment this when using mysql.

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge